"""CLI entry point for k33p.

Subcommands:

- ``k33p init``   — create a new k33p project
- ``k33p clone``  — clone a project from a local directory
- ``k33p tui``    — launch the TUI viewer
- ``k33p info``   — print project info and exit
- ``k33p store``  — content-addressed store operations
- ``k33p version``— print version and exit

When no subcommand is given, the first positional argument is treated as a
path and the TUI is launched (backward-compatible with ``k33p <path>``).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SUBCOMMANDS = frozenset({"init", "clone", "tui", "info", "store", "version"})


# ── subcommand handlers (defined here, dispatched from main) ──────────────


def _cmd_init(args: list[str]) -> int:
    """``k33p init`` — create a new k33p project."""
    parser = argparse.ArgumentParser(
        prog="k33p init",
        description="Create a new k33p project",
    )
    parser.add_argument("name", help="Project name")
    parser.add_argument(
        "--dir", "-d",
        default=".",
        help="Directory to create the project in (default: current dir)",
    )
    parser.add_argument(
        "--description", "-m",
        default="",
        help="Short project description",
    )
    parser.add_argument(
        "--org", default=None,
        help="Organisation or namespace",
    )
    parser.add_argument(
        "--type",
        default="single",
        choices=("single", "monorepo"),
        help="Project type (default: single)",
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing k33p.yaml if present",
    )
    parsed = parser.parse_args(args)

    target = Path(parsed.dir).resolve()
    yaml_path = target / "k33p.yaml"

    if yaml_path.exists() and not parsed.force:
        print(f"k33p: {yaml_path} already exists (use --force to overwrite)",
              file=sys.stderr)
        return 1

    name = parsed.name

    # Build a minimal k33p.yaml
    channels = f"""\
  src:
    type: source
    transport: git+https://example.com/{name}
    visibility: public
    history: full
"""

    yaml_lines = [f"# k33p.yaml — generated by `k33p init`"]
    yaml_lines.append(f"project: {name}")
    yaml_lines.append(f"type: {parsed.type}")
    if parsed.description:
        yaml_lines.append(f"description: {parsed.description}")
    if parsed.org:
        yaml_lines.append(f"org: {parsed.org}")
    yaml_lines.append("")
    yaml_lines.append("channels:")
    yaml_lines.append(channels)
    yaml_lines.append("views:")
    yaml_lines.append("  default:")
    yaml_lines.append("    src: { at: \"./\" }")
    yaml_lines.append("")
    yaml_lines.append("roles:")
    yaml_lines.append("  developer:   { view: default }")
    yaml_lines.append("")

    yaml_content = "\n".join(yaml_lines)

    target.mkdir(parents=True, exist_ok=True)
    yaml_path.write_text(yaml_content, encoding="utf-8")

    # Initialise the store
    store_path = target / ".k33p" / "store"
    store_path.mkdir(parents=True, exist_ok=True)
    (target / ".k33p" / ".gitkeep").write_text("")
    (target / ".k33p" / "store" / ".gitkeep").write_text("")

    print(f"✓ Initialised k33p project {name!r} at {target}")
    print(f"  manifest: {yaml_path}")
    print(f"  store:    {store_path}")
    print(f"  type:     {parsed.type}")
    print()
    print("Next steps:")
    print(f"  cd {target}")
    print("  k33p             # launch the TUI viewer")
    print("  k33p info        # show project info")
    return 0


def _cmd_tui(args: list[str]) -> int:
    """``k33p tui`` — launch the TUI viewer."""
    parser = argparse.ArgumentParser(
        prog="k33p tui",
        description="Launch the TUI viewer",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Path to project directory or k33p.yaml (default: .)",
    )
    parser.add_argument(
        "--subproject", "-s", default=None,
        help="Subproject to focus on (monorepo only)",
    )
    parser.add_argument(
        "--role", "-r", default=None,
        help="Role to use (default: from manifest)",
    )
    parsed = parser.parse_args(args)

    from k33p.project import load_project

    try:
        project = load_project(parsed.path)
    except FileNotFoundError as e:
        print(f"k33p: {e}", file=sys.stderr)
        return 2
    except Exception as e:
        print(f"k33p: failed to load project: {e}", file=sys.stderr)
        return 1

    if parsed.subproject:
        project.set_subproject(parsed.subproject)
    if parsed.role:
        project.set_role(parsed.role)

    from k33p.tui.app import K33pApp

    app = K33pApp(project)
    app.run()
    return 0


def _cmd_info(args: list[str]) -> int:
    """``k33p info`` — show project info and exit."""
    parser = argparse.ArgumentParser(
        prog="k33p info",
        description="Show project info and exit",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Path to project directory or k33p.yaml (default: .)",
    )
    parsed = parser.parse_args(args)

    from k33p.project import load_project

    try:
        project = load_project(parsed.path)
    except FileNotFoundError as e:
        print(f"k33p: {e}", file=sys.stderr)
        return 2
    except Exception as e:
        print(f"k33p: {e}", file=sys.stderr)
        return 1

    _print_summary(project)
    return 0


def _cmd_store(args: list[str]) -> int:
    """``k33p store`` — CAS operations."""
    if not args:
        print("k33p store: expected a subcommand (put, get, stats, ls)",
              file=sys.stderr)
        return 2

    store_cmd = args[0]
    rest = args[1:]

    from k33p.store import ContentStore

    if store_cmd == "put":
        parser = argparse.ArgumentParser(prog="k33p store put")
        parser.add_argument("path", help="Path to the project")
        parser.add_argument("file", help="Path to the file to store")
        parser.add_argument(
            "--kind", "-k", default="blob",
            help="Object kind (default: blob)",
        )
        parsed = parser.parse_args(rest)
        return _do_store_put(parsed, ContentStore)

    if store_cmd == "get":
        parser = argparse.ArgumentParser(prog="k33p store get")
        parser.add_argument("path", help="Path to the project")
        parser.add_argument("hash", help="SHA-256 hash of the object")
        parsed = parser.parse_args(rest)
        return _do_store_get(parsed, ContentStore)

    if store_cmd == "stats":
        parser = argparse.ArgumentParser(prog="k33p store stats")
        parser.add_argument("path", help="Path to the project")
        parsed = parser.parse_args(rest)
        return _do_store_stats(parsed, ContentStore)

    if store_cmd == "ls":
        parser = argparse.ArgumentParser(prog="k33p store ls")
        parser.add_argument("path", help="Path to the project")
        parsed = parser.parse_args(rest)
        return _do_store_ls(parsed, ContentStore)

    print(f"k33p store: unknown subcommand {store_cmd!r} "
          f"(choose from put, get, stats, ls)",
          file=sys.stderr)
    return 2


# ── store sub-subcommand implementations ────────────────────────────────


def _get_store(parsed_path: str, ContentStore_cls: type) -> tuple:
    """Load a project and return (ContentStore, project)."""
    from k33p.project import load_project

    try:
        project = load_project(parsed_path)
    except FileNotFoundError as e:
        print(f"k33p: {e}", file=sys.stderr)
        return None, None
    except Exception as e:
        print(f"k33p: {e}", file=sys.stderr)
        return None, None

    store_path = project.store_path or project.path / ".k33p" / "store"
    store = ContentStore_cls(store_path)
    return store, project


def _do_store_put(
    parsed: argparse.Namespace, ContentStore_cls: type,
) -> int:
    store, project = _get_store(parsed.path, ContentStore_cls)
    if store is None:
        return 2

    file_path = Path(parsed.file)
    if not file_path.exists():
        print(f"k33p: file not found: {file_path}", file=sys.stderr)
        return 1
    data = file_path.read_bytes()
    kind = parsed.kind
    hash_str = store.put(data, kind=kind)
    print(f"Stored as {hash_str}  ({kind}, {len(data)} bytes uncompressed)")
    return 0


def _do_store_get(
    parsed: argparse.Namespace, ContentStore_cls: type,
) -> int:
    store, project = _get_store(parsed.path, ContentStore_cls)
    if store is None:
        return 2

    data = store.get(parsed.hash)
    if data is None:
        print(f"k33p: object not found: {parsed.hash}", file=sys.stderr)
        return 1
    kind = store.get_kind(parsed.hash)
    print(f"# kind={kind}  size={len(data)}")
    sys.stdout.buffer.write(data)
    if data and data[-1:] != b"\n":
        sys.stdout.buffer.write(b"\n")
    return 0


def _do_store_stats(
    parsed: argparse.Namespace, ContentStore_cls: type,
) -> int:
    store, project = _get_store(parsed.path, ContentStore_cls)
    if store is None:
        return 2

    stats = store.stats()
    mb_comp = stats.compressed_bytes / 1024 / 1024
    mb_uncomp = stats.total_bytes / 1024 / 1024
    print(f"Objects:   {stats.object_count}")
    print(f"Size:      {mb_uncomp:.2f} MB uncompressed, "
          f"{mb_comp:.2f} MB on disk")
    print(f"Shards:    {stats.shard_count}")
    if stats.object_count > 0:
        avg = stats.total_bytes / stats.object_count
        print(f"Avg obj:   {avg:.0f} bytes")
    return 0


def _do_store_ls(
    parsed: argparse.Namespace, ContentStore_cls: type,
) -> int:
    store, project = _get_store(parsed.path, ContentStore_cls)
    if store is None:
        return 2

    print(f"{'Hash':64}  {'Kind':12}  {'Size':>8}")
    print("-" * 88)
    for obj in store.iter_objects():
        print(f"{obj.hash:64}  {obj.kind:12}  {obj.size:>8}")
    return 0


# ── main dispatcher ─────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    """Run the k33p CLI.

    Manual dispatch to avoid argparse subparser complications, and to
    preserve backward compatibility: ``k33p <path>`` launches the TUI.
    """
    args = list(argv) if argv is not None else sys.argv[1:]

    if args and args[0] in SUBCOMMANDS:
        cmd = args[0]
        rest = args[1:]
    else:
        cmd = "tui"  # default (backward compat)
        rest = args   # ``k33p <path>`` → rest = [path]

    dispatch = {
        "init": _cmd_init,
        "clone": _cmd_clone,
        "tui": _cmd_tui,
        "info": _cmd_info,
        "store": _cmd_store,
        "version": _cmd_version,
    }

    handler = dispatch.get(cmd)
    if handler is None:
        print(f"k33p: unknown command {cmd!r}", file=sys.stderr)
        return 2
    return handler(rest)


def _cmd_clone(args: list[str]) -> int:
    """``k33p clone`` — clone a project from a source directory."""
    parser = argparse.ArgumentParser(
        prog="k33p clone",
        description="Clone a k33p project from a source directory",
    )
    parser.add_argument(
        "source",
        help="Source path or file:// URL",
    )
    parser.add_argument(
        "target",
        nargs="?",
        default=None,
        help="Target directory (default: <project-name> in current dir)",
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing k33p.yaml in target",
    )
    parsed = parser.parse_args(args)

    from k33p.transport import clone as _clone_project

    return _clone_project(parsed.source, parsed.target, force=parsed.force)


def _cmd_version(args: list[str]) -> int:
    """``k33p version`` — print version and exit."""
    from k33p.__about__ import __version__
    print(f"k33p {__version__}")
    return 0


# ── shared helpers ──────────────────────────────────────────────────────


def _print_summary(project) -> None:
    """Print a short summary of the loaded project."""
    m = project.manifest
    print(f"Project: {m.project} ({m.type})")
    if m.description:
        print(f"  {m.description}")
    if m.org or m.team:
        loc = " / ".join(filter(None, [m.org, m.team]))
        print(f"  org/team: {loc}")
    print(f"  manifest: {m.path}")
    print(f"  {len(m.channels)} channels, {len(m.subprojects)} subprojects, "
          f"{len(m.roles)} roles, {len(m.views)} views")
    if project.root_lock:
        print(f"  lock: {project.root_lock.path} "
              f"({len(project.root_lock.channels)} channel pins)")
    if project.store_path:
        from k33p.store import ContentStore
        stats = ContentStore(project.store_path).stats()
        print(f"  store: {stats.object_count} objects, "
              f"{stats.total_bytes / 1024 / 1024:.1f} MB")
    else:
        print("  store: not initialised (run `k33p init`)")


if __name__ == "__main__":
    raise SystemExit(main())
