"""CLI entry point for k33p.

Subcommands:

- ``k33p init``   — create a new k33p project
- ``k33p clone``   — clone a project from a local directory
- ``k33p sync``    — pull updates for the current project
- ``k33p import``  — import an external project (git, etc.)
- ``k33p daemon`` — run the auto-commit daemon
- ``k33p pointer`` — manage live channel pointers
- ``k33p org``     — manage permissions and access
- ``k33p split``   — split a subproject into a standalone project
- ``k33p convert`` — convert project to another format (WIP)
- ``k33p lock verify <path>`` — verify lockfile signature
- ``k33p tui``    — launch the TUI viewer
- ``k33p info``   — print project info and exit
- ``k33p store``  — content-addressed store operations
- ``k33p version``— print version and exit

When no subcommand is given, the first positional argument is treated as a
path and the TUI is launched (backward-compatible with ``k33p <path>``).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SUBCOMMANDS = frozenset({"init", "clone", "sync", "import", "daemon", "tui", "info", "store", "pointer", "org", "split", "convert", "lock", "serve", "get", "version"})


# ── subcommand handlers (defined here, dispatched from main) ──────────────


def _cmd_init(args: list[str]) -> int:
    """``k33p init`` — create a new k33p project."""
    parser = argparse.ArgumentParser(
        prog="k33p init",
        description="Create a new k33p project",
    )
    parser.add_argument("name", help="Project name")
    parser.add_argument(
        "--dir", "-d",
        default=".",
        help="Directory to create the project in (default: current dir)",
    )
    parser.add_argument(
        "--description", "-m",
        default="",
        help="Short project description",
    )
    parser.add_argument(
        "--org", default=None,
        help="Organisation or namespace",
    )
    parser.add_argument(
        "--type",
        default="single",
        choices=("single", "monorepo"),
        help="Project type (default: single)",
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing k33p.yaml if present",
    )
    parsed = parser.parse_args(args)

    target = Path(parsed.dir).resolve()
    yaml_path = target / "k33p.yaml"

    if yaml_path.exists() and not parsed.force:
        print(f"k33p: {yaml_path} already exists (use --force to overwrite)",
              file=sys.stderr)
        return 1

    name = parsed.name

    # Build a minimal k33p.yaml
    channels = f"""\
  src:
    type: source
    transport: git+https://example.com/{name}
    visibility: public
    history: full
"""

    yaml_lines = [f"# k33p.yaml — generated by `k33p init`"]
    yaml_lines.append(f"project: {name}")
    yaml_lines.append(f"type: {parsed.type}")
    if parsed.description:
        yaml_lines.append(f"description: {parsed.description}")
    if parsed.org:
        yaml_lines.append(f"org: {parsed.org}")
    yaml_lines.append("")
    yaml_lines.append("channels:")
    yaml_lines.append(channels)
    yaml_lines.append("views:")
    yaml_lines.append("  default:")
    yaml_lines.append("    src: { at: \"./\" }")
    yaml_lines.append("")
    yaml_lines.append("roles:")
    yaml_lines.append("  developer:   { view: default }")
    yaml_lines.append("")

    yaml_content = "\n".join(yaml_lines)

    target.mkdir(parents=True, exist_ok=True)
    yaml_path.write_text(yaml_content, encoding="utf-8")

    # Initialise the store
    store_path = target / ".k33p" / "store"
    store_path.mkdir(parents=True, exist_ok=True)
    (target / ".k33p" / ".gitkeep").write_text("")
    (target / ".k33p" / "store" / ".gitkeep").write_text("")

    print(f"✓ Initialised k33p project {name!r} at {target}")
    print(f"  manifest: {yaml_path}")
    print(f"  store:    {store_path}")
    print(f"  type:     {parsed.type}")
    print()
    print("Next steps:")
    print(f"  cd {target}")
    print("  k33p             # launch the TUI viewer")
    print("  k33p info        # show project info")
    return 0


def _cmd_tui(args: list[str]) -> int:
    """``k33p tui`` — launch the TUI viewer."""
    parser = argparse.ArgumentParser(
        prog="k33p tui",
        description="Launch the TUI viewer",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Path to project directory or k33p.yaml (default: .)",
    )
    parser.add_argument(
        "--subproject", "-s", default=None,
        help="Subproject to focus on (monorepo only)",
    )
    parser.add_argument(
        "--role", "-r", default=None,
        help="Role to use (default: from manifest)",
    )
    parsed = parser.parse_args(args)

    from k33p.project import load_project

    try:
        project = load_project(parsed.path)
    except FileNotFoundError as e:
        print(f"k33p: {e}", file=sys.stderr)
        return 2
    except Exception as e:
        print(f"k33p: failed to load project: {e}", file=sys.stderr)
        return 1

    if parsed.subproject:
        project.set_subproject(parsed.subproject)
    if parsed.role:
        project.set_role(parsed.role)

    from k33p.tui.app import K33pApp

    app = K33pApp(project)
    app.run()
    return 0


def _cmd_info(args: list[str]) -> int:
    """``k33p info`` — show project info and exit."""
    parser = argparse.ArgumentParser(
        prog="k33p info",
        description="Show project info and exit",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Path to project directory or k33p.yaml (default: .)",
    )
    parsed = parser.parse_args(args)

    from k33p.project import load_project

    try:
        project = load_project(parsed.path)
    except FileNotFoundError as e:
        print(f"k33p: {e}", file=sys.stderr)
        return 2
    except Exception as e:
        print(f"k33p: {e}", file=sys.stderr)
        return 1

    _print_summary(project)
    return 0


def _cmd_store(args: list[str]) -> int:
    """``k33p store`` — CAS operations."""
    if not args:
        print("k33p store: expected a subcommand (put, get, stats, ls)",
              file=sys.stderr)
        return 2

    store_cmd = args[0]
    rest = args[1:]

    from k33p.store import ContentStore

    if store_cmd == "put":
        parser = argparse.ArgumentParser(prog="k33p store put")
        parser.add_argument("path", help="Path to the project")
        parser.add_argument("file", help="Path to the file to store")
        parser.add_argument(
            "--kind", "-k", default="blob",
            help="Object kind (default: blob)",
        )
        parsed = parser.parse_args(rest)
        return _do_store_put(parsed, ContentStore)

    if store_cmd == "get":
        parser = argparse.ArgumentParser(prog="k33p store get")
        parser.add_argument("path", help="Path to the project")
        parser.add_argument("hash", help="SHA-256 hash of the object")
        parsed = parser.parse_args(rest)
        return _do_store_get(parsed, ContentStore)

    if store_cmd == "stats":
        parser = argparse.ArgumentParser(prog="k33p store stats")
        parser.add_argument("path", help="Path to the project")
        parsed = parser.parse_args(rest)
        return _do_store_stats(parsed, ContentStore)

    if store_cmd == "ls":
        parser = argparse.ArgumentParser(prog="k33p store ls")
        parser.add_argument("path", help="Path to the project")
        parsed = parser.parse_args(rest)
        return _do_store_ls(parsed, ContentStore)

    if store_cmd == "verify":
        parser = argparse.ArgumentParser(prog="k33p store verify")
        parser.add_argument("path", help="Path to the project")
        parsed = parser.parse_args(rest)
        return _do_store_verify(parsed, ContentStore)

    if store_cmd == "gc":
        parser = argparse.ArgumentParser(prog="k33p store gc")
        parser.add_argument("path", help="Path to the project")
        parser.add_argument(
            "--dry-run", "-n",
            action="store_true",
            help="Only report what would be removed, do not delete",
        )
        parsed = parser.parse_args(rest)
        return _do_store_gc(parsed, ContentStore)

    print(f"k33p store: unknown subcommand {store_cmd!r} "
          f"(choose from put, get, stats, ls, verify, gc)",
          file=sys.stderr)
    return 2


# ── store sub-subcommand implementations ────────────────────────────────


def _get_store(parsed_path: str, ContentStore_cls: type) -> tuple:
    """Load a project and return (ContentStore, project)."""
    from k33p.project import load_project

    try:
        project = load_project(parsed_path)
    except FileNotFoundError as e:
        print(f"k33p: {e}", file=sys.stderr)
        return None, None
    except Exception as e:
        print(f"k33p: {e}", file=sys.stderr)
        return None, None

    store_path = project.store_path or project.path / ".k33p" / "store"
    store = ContentStore_cls(store_path)
    return store, project


def _do_store_put(
    parsed: argparse.Namespace, ContentStore_cls: type,
) -> int:
    store, project = _get_store(parsed.path, ContentStore_cls)
    if store is None:
        return 2

    file_path = Path(parsed.file)
    if not file_path.exists():
        print(f"k33p: file not found: {file_path}", file=sys.stderr)
        return 1
    data = file_path.read_bytes()
    kind = parsed.kind
    hash_str = store.put(data, kind=kind)
    print(f"Stored as {hash_str}  ({kind}, {len(data)} bytes uncompressed)")
    return 0


def _do_store_get(
    parsed: argparse.Namespace, ContentStore_cls: type,
) -> int:
    store, project = _get_store(parsed.path, ContentStore_cls)
    if store is None:
        return 2

    data = store.get(parsed.hash)
    if data is None:
        print(f"k33p: object not found: {parsed.hash}", file=sys.stderr)
        return 1
    kind = store.get_kind(parsed.hash)
    print(f"# kind={kind}  size={len(data)}")
    sys.stdout.buffer.write(data)
    if data and data[-1:] != b"\n":
        sys.stdout.buffer.write(b"\n")
    return 0


def _do_store_stats(
    parsed: argparse.Namespace, ContentStore_cls: type,
) -> int:
    store, project = _get_store(parsed.path, ContentStore_cls)
    if store is None:
        return 2

    stats = store.stats()
    mb_comp = stats.compressed_bytes / 1024 / 1024
    mb_uncomp = stats.total_bytes / 1024 / 1024
    print(f"Objects:   {stats.object_count}")
    print(f"Size:      {mb_uncomp:.2f} MB uncompressed, "
          f"{mb_comp:.2f} MB on disk")
    print(f"Shards:    {stats.shard_count}")
    if stats.object_count > 0:
        avg = stats.total_bytes / stats.object_count
        print(f"Avg obj:   {avg:.0f} bytes")
    return 0


def _do_store_ls(
    parsed: argparse.Namespace, ContentStore_cls: type,
) -> int:
    store, project = _get_store(parsed.path, ContentStore_cls)
    if store is None:
        return 2

    print(f"{'Hash':64}  {'Kind':12}  {'Size':>8}")
    print("-" * 88)
    for obj in store.iter_objects():
        print(f"{obj.hash:64}  {obj.kind:12}  {obj.size:>8}")
    return 0


def _do_store_verify(
    parsed: argparse.Namespace, ContentStore_cls: type,
) -> int:
    store, project = _get_store(parsed.path, ContentStore_cls)
    if store is None:
        return 2

    result = store.verify()
    print(f"Verification complete:")
    print(f"  total:     {result.total}")
    print(f"  ok:        {result.ok}")
    print(f"  corrupted: {result.corrupted}")
    if result.errors:
        print(f"\nErrors ({len(result.errors)}):")
        for err in result.errors[:10]:
            print(f"  • {err}")
        if len(result.errors) > 10:
            print(f"  ... and {len(result.errors) - 10} more")
        return 1
    return 0


def _do_store_gc(
    parsed: argparse.Namespace, ContentStore_cls: type,
) -> int:
    store, project = _get_store(parsed.path, ContentStore_cls)
    if store is None:
        return 2

    removed = store.gc(dry_run=parsed.dry_run)
    if parsed.dry_run:
        print(f"GC dry-run: {removed} object(s) would be removed")
        if removed == 0:
            print("Store is clean.")
    else:
        print(f"GC complete: {removed} object(s) removed")
        if removed == 0:
            print("Store is clean.")
    return 0


# ── main dispatcher ─────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    """Run the k33p CLI.

    Manual dispatch to avoid argparse subparser complications, and to
    preserve backward compatibility: ``k33p <path>`` launches the TUI.
    """
    args = list(argv) if argv is not None else sys.argv[1:]

    if args and args[0] in SUBCOMMANDS:
        cmd = args[0]
        rest = args[1:]
    else:
        cmd = "tui"  # default (backward compat)
        rest = args   # ``k33p <path>`` → rest = [path]

    dispatch = {
        "init": _cmd_init,
        "clone": _cmd_clone,
        "sync": _cmd_sync,
        "import": _cmd_import,
        "daemon": _cmd_daemon,
        "tui": _cmd_tui,
        "info": _cmd_info,
        "store": _cmd_store,
        "pointer": _cmd_pointer,
        "org": _cmd_org,
        "split": _cmd_split,
        "convert": _cmd_convert,
        "lock": _cmd_lock,
        "serve": _cmd_serve,
        "get": _cmd_get,
        "version": _cmd_version,
    }

    handler = dispatch.get(cmd)
    if handler is None:
        print(f"k33p: unknown command {cmd!r}", file=sys.stderr)
        return 2
    return handler(rest)


def _cmd_clone(args: list[str]) -> int:
    """``k33p clone`` — clone a project from a source directory."""
    parser = argparse.ArgumentParser(
        prog="k33p clone",
        description="Clone a k33p project from a source directory",
    )
    parser.add_argument(
        "source",
        help="Source path or file:// URL",
    )
    parser.add_argument(
        "target",
        nargs="?",
        default=None,
        help="Target directory (default: <project-name> in current dir)",
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing k33p.yaml in target",
    )
    parsed = parser.parse_args(args)

    from k33p.transport import clone as _clone_project

    return _clone_project(parsed.source, parsed.target, force=parsed.force)


def _cmd_import(args: list[str]) -> int:
    """``k33p import`` — import an external project."""
    parser = argparse.ArgumentParser(
        prog="k33p import",
        description="Import an external project as a k33p project",
    )
    parser.add_argument(
        "--from-git",
        required=True,
        help="Git repository URL to import from",
    )
    parser.add_argument(
        "target",
        nargs="?",
        default=None,
        help="Target directory (default: repo name in current dir)",
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing files",
    )
    parsed = parser.parse_args(args)

    from k33p.transport import import_from_git

    return import_from_git(parsed.from_git, parsed.target, force=parsed.force)


def _cmd_pointer(args: list[str]) -> int:
    """``k33p pointer`` — manage live channel pointers."""
    if not args:
        print("k33p pointer: expected a subcommand (set, list)", file=sys.stderr)
        return 2

    sub = args[0]
    rest = args[1:]

    if sub == "set":
        parser = argparse.ArgumentParser(prog="k33p pointer set")
        parser.add_argument("name", help="Pointer name")
        parser.add_argument("target", help="Target ref (e.g. src@main)")
        parser.add_argument(
            "--reason", "-m", default=None, help="Reason for the update"
        )
        parser.add_argument(
            "--sign-with", default=None, help="Key to sign with"
        )
        parser.add_argument(
            "--force", "-f", action="store_true",
            help="Skip rate-limit check"
        )
        parser.add_argument(
            "path", nargs="?", default=".",
            help="Project path (default: .)"
        )
        parsed = parser.parse_args(rest)
        from k33p.pointer import cmd_pointer_set
        return cmd_pointer_set(
            parsed.path, parsed.name, parsed.target,
            reason=parsed.reason,
            sign_with=parsed.sign_with,
            force=parsed.force,
        )

    if sub == "list":
        parser = argparse.ArgumentParser(prog="k33p pointer list")
        parser.add_argument(
            "path", nargs="?", default=".",
            help="Project path (default: .)"
        )
        parsed = parser.parse_args(rest)
        from k33p.pointer import cmd_pointer_list
        return cmd_pointer_list(parsed.path)

    print(f"k33p pointer: unknown subcommand {sub!r}", file=sys.stderr)
    return 2


def _cmd_org(args: list[str]) -> int:
    """``k33p org`` — manage permissions and access."""
    if not args:
        print("k33p org: expected a subcommand (grant, revoke, list)",
              file=sys.stderr)
        return 2

    sub = args[0]
    rest = args[1:]

    if sub == "grant":
        parser = argparse.ArgumentParser(prog="k33p org grant")
        parser.add_argument("subject", help="Team or user (e.g. games-team)")
        parser.add_argument(
            "--role", default="read",
            choices=("read", "write", "admin"),
            help="Access level (default: read)",
        )
        parser.add_argument(
            "--subproject", "-s", default=None,
            help="Subproject to scope the grant to",
        )
        parser.add_argument(
            "path", nargs="?", default=".",
            help="Project path (default: .)",
        )
        parsed = parser.parse_args(rest)
        from k33p.access import cmd_grant
        return cmd_grant(
            parsed.path, parsed.subject,
            role=parsed.role, subproject=parsed.subproject,
        )

    if sub == "revoke":
        parser = argparse.ArgumentParser(prog="k33p org revoke")
        parser.add_argument("subject", help="Team or user")
        parser.add_argument(
            "--role", default=None,
            help="Access level to revoke (omit to revoke all)",
        )
        parser.add_argument(
            "--subproject", "-s", default=None,
            help="Subproject scope",
        )
        parser.add_argument(
            "path", nargs="?", default=".",
            help="Project path (default: .)",
        )
        parsed = parser.parse_args(rest)
        from k33p.access import cmd_revoke
        return cmd_revoke(
            parsed.path, parsed.subject,
            role=parsed.role, subproject=parsed.subproject,
        )

    if sub in ("list", "show", "permissions"):
        parser = argparse.ArgumentParser(prog="k33p org list")
        parser.add_argument(
            "path", nargs="?", default=".",
            help="Project path (default: .)",
        )
        parsed = parser.parse_args(rest)
        from k33p.access import cmd_permissions
        return cmd_permissions(parsed.path)

    print(f"k33p org: unknown subcommand {sub!r}", file=sys.stderr)
    return 2


def _cmd_split(args: list[str]) -> int:
    """``k33p split`` — split a subproject into a standalone project."""
    parser = argparse.ArgumentParser(
        prog="k33p split",
        description="Split a subproject from a monorepo into a standalone project",
    )
    parser.add_argument(
        "subproject",
        help="Name of the subproject to split out",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Path to the monorepo (default: .)",
    )
    parser.add_argument(
        "--target", "-t",
        default=None,
        help="Target directory (default: <subproject-name> in cwd)",
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing files",
    )
    parsed = parser.parse_args(args)

    from k33p.migrate import cmd_split
    return cmd_split(parsed.path, parsed.subproject, parsed.target, force=parsed.force)


def _cmd_convert(args: list[str]) -> int:
    """``k33p convert`` — convert project to another format."""
    parser = argparse.ArgumentParser(
        prog="k33p convert",
        description="Convert a k33p project to another format",
    )
    parser.add_argument(
        "--to",
        required=True,
        choices=("oci-image", "flat-dir"),
        help="Target format",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Path to the project (default: .)",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Output path",
    )
    parsed = parser.parse_args(args)

    from k33p.migrate import cmd_convert
    return cmd_convert(parsed.path, parsed.to, output=parsed.output)


def _cmd_lock(args: list[str]) -> int:
    """``k33p lock`` — lockfile operations."""
    if not args:
        print("k33p lock: expected a subcommand (verify)", file=sys.stderr)
        return 2

    sub = args[0]
    rest = args[1:]

    if sub == "verify":
        parser = argparse.ArgumentParser(prog="k33p lock verify")
        parser.add_argument(
            "path",
            nargs="?",
            default=".",
            help="Path to k33p.lock or project directory (default: .)",
        )
        parser.add_argument(
            "--key", default=None,
            help="Path to public key file",
        )
        parsed = parser.parse_args(rest)

        # Resolve the lock file path
        lock_path = Path(parsed.path)
        if lock_path.is_dir():
            lock_path = lock_path / "k33p.lock"
        if not lock_path.exists():
            print(f"k33p: lock file not found: {lock_path}", file=sys.stderr)
            return 1

        from k33p.sig import verify_lock_signature, VerifyError

        try:
            valid, msg = verify_lock_signature(lock_path, key_path=parsed.key)
        except VerifyError as e:
            print(f"k33p: {e}", file=sys.stderr)
            return 1

        if valid:
            print(f"{lock_path}: {msg}")
            return 0
        else:
            print(f"{lock_path}: {msg}", file=sys.stderr)
            return 1

    print(f"k33p lock: unknown subcommand {sub!r}", file=sys.stderr)
    return 2


def _cmd_serve(args: list[str]) -> int:
    """``k33p serve`` — start HTTP server to share store objects."""
    parser = argparse.ArgumentParser(
        prog="k33p serve",
        description="Start an HTTP server to share store objects with peers",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Path to the project (default: .)",
    )
    parser.add_argument(
        "--host", default="127.0.0.1",
        help="Host to bind to (default: 127.0.0.1)",
    )
    parser.add_argument(
        "--port", "-p", type=int, default=8734,
        help="Port to listen on (default: 8734)",
    )
    parsed = parser.parse_args(args)

    from k33p.project import load_project

    try:
        project = load_project(parsed.path)
    except FileNotFoundError as e:
        print(f"k33p: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"k33p: {e}", file=sys.stderr)
        return 1

    from k33p.transport_k33p import serve_store
    store_path = project.store_path or (project.path / ".k33p" / "store")
    serve_store(store_path, host=parsed.host, port=parsed.port)
    return 0


def _cmd_get(args: list[str]) -> int:
    """``k33p get`` — fetch an object from a k33p:// peer."""
    parser = argparse.ArgumentParser(
        prog="k33p get",
        description="Fetch an object from a k33p:// peer via HTTP",
    )
    parser.add_argument(
        "url",
        help="k33p://host:port/hash URL",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Target project path (default: .)",
    )
    parsed = parser.parse_args(args)

    from k33p.store import ContentStore
    from k33p.project import load_project
    from k33p.transport_k33p import K33pTransport

    url = parsed.url
    if not url.startswith("k33p://"):
        print(f"k33p: invalid URL {url!r} (must start with k33p://)",
              file=sys.stderr)
        return 1

    rest = url[7:]
    if "/" not in rest:
        print(f"k33p: URL must include a hash: {url}", file=sys.stderr)
        return 1
    host_port, hash_str = rest.split("/", 1)
    source = f"k33p://{host_port}"

    # Resolve store path
    store_dir = Path(parsed.path)
    from k33p.project import load_project as lp
    try:
        proj = lp(str(store_dir))
        store_path = proj.store_path or (store_dir / ".k33p" / "store")
    except Exception:
        store_path = store_dir / ".k33p" / "store"

    store = ContentStore(store_path)
    store.ensure()

    transport = K33pTransport(source)
    from k33p.transport import TransportError
    try:
        data = transport.get_object(store, hash_str)
    except TransportError as e:
        print(f"k33p: {e}", file=sys.stderr)
        return 1

    if data is None:
        print(f"k33p: object not found at {source}", file=sys.stderr)
        return 1

    kind = store.get_kind(hash_str)
    print(f"✓ Fetched {hash_str[:16]} ({kind}, {len(data)} bytes) from {source}")
    return 0


def _cmd_daemon(args: list[str]) -> int:
    """``k33p daemon`` — run the auto-commit daemon."""
    parser = argparse.ArgumentParser(
        prog="k33p daemon",
        description="Run the k33p auto-commit daemon",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=None,
        help="Path to the project directory (default: current dir)",
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Run a single check and exit (for testing)",
    )
    parsed = parser.parse_args(args)

    from k33p.daemon import run_daemon

    return run_daemon(parsed.path, once=parsed.once)


def _cmd_sync(args: list[str]) -> int:
    """``k33p sync`` — pull updates from upstream sources."""
    parser = argparse.ArgumentParser(
        prog="k33p sync",
        description="Pull updates for the current project from upstream sources",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=None,
        help="Path to the project directory (default: current dir)",
    )
    parsed = parser.parse_args(args)

    from k33p.transport import sync as _sync_project

    path = parsed.path or "."
    return _sync_project(path)


def _cmd_version(args: list[str]) -> int:
    """``k33p version`` — print version and exit."""
    from k33p.__about__ import __version__
    print(f"k33p {__version__}")
    return 0


# ── shared helpers ──────────────────────────────────────────────────────


def _print_summary(project) -> None:
    """Print a short summary of the loaded project."""
    m = project.manifest
    print(f"Project: {m.project} ({m.type})")
    if m.description:
        print(f"  {m.description}")
    if m.org or m.team:
        loc = " / ".join(filter(None, [m.org, m.team]))
        print(f"  org/team: {loc}")
    print(f"  manifest: {m.path}")
    print(f"  {len(m.channels)} channels, {len(m.subprojects)} subprojects, "
          f"{len(m.roles)} roles, {len(m.views)} views")
    if project.root_lock:
        print(f"  lock: {project.root_lock.path} "
              f"({len(project.root_lock.channels)} channel pins)")
    if project.store_path:
        from k33p.store import ContentStore
        stats = ContentStore(project.store_path).stats()
        print(f"  store: {stats.object_count} objects, "
              f"{stats.total_bytes / 1024 / 1024:.1f} MB")
    else:
        print("  store: not initialised (run `k33p init`)")


if __name__ == "__main__":
    raise SystemExit(main())
