#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw

from compare_pi_screenshots import compare_images, save_diff_report

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = ROOT / "artifacts" / "ui-automation-demo"


def draw_demo_screen(path: Path, *, variant: str) -> None:
    width, height = 960, 600
    image = Image.new("RGBA", (width, height), "#0f172a")
    draw = ImageDraw.Draw(image)

    header_color = "#1e293b" if variant == "baseline" else "#111827"
    header_accent = "#60a5fa" if variant == "baseline" else "#34d399"
    button_color = "#2563eb" if variant == "baseline" else "#10b981"
    warning_color = "#f59e0b" if variant == "baseline" else "#ef4444"

    draw.rounded_rectangle((24, 20, width - 24, 110), radius=20, fill=header_color)
    draw.text((54, 42), "Project dashboard", fill="white")
    draw.text((54, 72), "Overview of builds, alerts, and deployment health", fill="#cbd5e1")
    draw.rounded_rectangle((width - 220, 38, width - 54, 88), radius=16, fill=button_color)
    draw.text((width - 185, 56), "Primary action", fill="white")
    draw.rounded_rectangle((width - 250, 98, width - 54, 102), radius=2, fill=header_accent)

    card_top = 150
    for index in range(3):
        left = 40 + index * 300
        right = left + 260
        draw.rounded_rectangle((left, card_top, right, 330), radius=18, fill="#111827")
        draw.text((left + 24, card_top + 24), f"Metric {index + 1}", fill="#e5e7eb")
        draw.text((left + 24, card_top + 72), ["12 builds", "3 alerts", "97% pass"][index], fill="white")
        if variant == "current" and index == 1:
            draw.rounded_rectangle((left + 18, card_top + 126, right - 18, card_top + 170), radius=12, fill=warning_color)
            draw.text((left + 34, card_top + 142), "Needs attention", fill="white")
        else:
            draw.rounded_rectangle((left + 24, card_top + 126, right - 24, card_top + 170), radius=12, fill="#1f2937")
            draw.text((left + 40, card_top + 142), "Healthy", fill="#cbd5e1")

    draw.rounded_rectangle((40, 372, width - 40, height - 40), radius=18, fill="#111827")
    draw.text((68, 400), "Recent activity", fill="#e5e7eb")
    row_y = 448
    for idx in range(4):
        left_pad = 68 if variant == "baseline" else 80
        right_pad = width - (92 if variant == "baseline" else 76)
        draw.rounded_rectangle((left_pad, row_y + idx * 32, right_pad, row_y + 18 + idx * 32), radius=8, fill="#1f2937")

    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def write_demo_readme(output_dir: Path, *, baseline: Path, current: Path, diff: Path, diff_json: Path) -> None:
    readme = output_dir / "README.md"
    readme.write_text(
        f"""# UI Automation Demo Artifacts

This directory was generated by `demo_ui_automation.py`.

Artifacts:

- `baseline.png`
- `current.png`
- `diff.png`
- `diff.json`

Suggested next commands:

```bash
python3 ./pi-skills/pi-extension-testing/scripts/compare_pi_screenshots.py {baseline} {current} --output-dir {output_dir}
```

```bash
pi -p --no-extensions -e ./pi-packages/pi-ui-heuristic-critique @{baseline} @{current} @{diff} "/ui-heuristic-score demo dashboard regression\n\nDiff metadata:\n$(cat {diff_json})"
```

```bash
pi -e ./pi-packages/pi-subagents "/ui-autopolish tighten the demo dashboard layout using {output_dir / 'README.md'} and {output_dir / 'diff.json'}"
```
""",
        encoding="utf-8",
    )


def build_demo(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    baseline = output_dir / "baseline.png"
    current = output_dir / "current.png"
    diff = output_dir / "diff.png"
    diff_json = output_dir / "diff.json"

    draw_demo_screen(baseline, variant="baseline")
    draw_demo_screen(current, variant="current")
    stats = compare_images(baseline, current, diff)
    save_diff_report(stats, diff_json)
    write_demo_readme(output_dir, baseline=baseline, current=current, diff=diff, diff_json=diff_json)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate demo artifacts that show off the new Pi UI automation workflow")
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR), help="Directory for the generated demo artifacts")
    args = parser.parse_args()
    build_demo(Path(args.output_dir).expanduser().resolve())
    print(Path(args.output_dir).expanduser().resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
