# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen', models.IntegerField(default=100)),
                ('heat', models.IntegerField(default=50)),
                ('cooling', models.BooleanField(default=True)),
                ('fuel', models.IntegerField(default=100)),
                ('current_shield', models.CharField(default='aaaa', max_length=4)),
                ('ideal_shield', models.CharField(default='aaaa', max_length=4)),
                ('gps', models.CharField(default='000000', max_length=6)),
                ('self_destruct', models.BooleanField(default=False)),
                ('ftl_on', models.BooleanField(default=True)),
            ],
        ),
    ]
