# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='health',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='ship',
            name='multiplier',
            field=models.FloatField(default=0.001),
        ),
        migrations.AddField(
            model_name='ship',
            name='planet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='fuel',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='ship',
            name='heat',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='ship',
            name='oxygen',
            field=models.FloatField(default=100),
        ),
    ]
