# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i3', '0004_auto_20171118_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='distance_to_planet',
            field=models.FloatField(default=10000),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ftl_on',
            field=models.BooleanField(default=False),
        ),
    ]
