# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i3', '0005_auto_20171118_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='engine_fuel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='multiplier',
            field=models.FloatField(default=0.1),
        ),
    ]
