from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PUZZLE_BANK_PATH = PROJECT_ROOT / "data" / "puzzles.json"
BASE_PUZZLE_IDS = {
    "goto-fail-inspired",
    "dao-reentrancy-inspired",
    "ariane-overflow-inspired",
}
BUG_MARKER = "<<BUG>>"
TOKEN_PATTERN = re.compile(r"\[\[([a-z0-9_]+)\]\]")


@dataclass(frozen=True)
class PuzzleTemplate:
    key: str
    language: str
    issue_category: str
    issue_type: str
    title: str
    source_note: str
    summary: str
    explanation: str
    hints: tuple[str, ...]
    code: tuple[str, ...]
    variants: tuple[Mapping[str, str], ...]


def substitute(text: str, values: Mapping[str, str]) -> str:
    def replace(match: re.Match[str]) -> str:
        key = match.group(1)
        return str(values[key])

    return TOKEN_PATTERN.sub(replace, text)


def render_puzzle(template: PuzzleTemplate, variant: Mapping[str, str]) -> dict[str, object]:
    values = dict(variant)
    values.setdefault("identifier_slug", values["slug"].replace("-", "_"))

    code_lines: list[str] = []
    answer_line: int | None = None
    for raw_line in template.code:
        rendered = substitute(raw_line, values)
        if BUG_MARKER in rendered:
            if answer_line is not None:
                raise ValueError(f"Template {template.key} has multiple bug markers.")
            answer_line = len(code_lines) + 1
            rendered = rendered.replace(BUG_MARKER, "")
        code_lines.append(rendered)
    if answer_line is None:
        raise ValueError(f"Template {template.key} is missing a bug marker.")
    while len(code_lines) < 25:
        code_lines.append("")

    values["answer_line"] = str(answer_line)
    return {
        "id": f"{template.key}-{variant['slug']}",
        "title": substitute(template.title, values),
        "language": template.language,
        "source_note": substitute(template.source_note, values),
        "summary": substitute(template.summary, values),
        "code": code_lines,
        "answer_line": answer_line,
        "issue_category": template.issue_category,
        "issue_type": template.issue_type,
        "explanation": substitute(template.explanation, values),
        "hints": [substitute(hint, values) for hint in template.hints],
    }


def load_base_puzzles() -> list[dict[str, object]]:
    existing_items = json.loads(PUZZLE_BANK_PATH.read_text(encoding="utf-8"))
    base_items = [item for item in existing_items if item["id"] in BASE_PUZZLE_IDS]
    if len(base_items) != len(BASE_PUZZLE_IDS):
        missing_ids = sorted(BASE_PUZZLE_IDS - {item["id"] for item in base_items})
        raise ValueError(f"Missing base puzzles: {missing_ids}")
    return base_items


def templates() -> tuple[PuzzleTemplate, ...]:
    return (
        PuzzleTemplate(
            key="signature-gate-bypass",
            language="C",
            issue_category="Security and trust",
            issue_type="Security check bypass",
            title="[[subject]] Signature Gate",
            source_note="Inspired by early-return verification bugs in signature and package-validation paths.",
            summary="Review this verifier and find the line that quietly turns the final signature check into dead code.",
            explanation="The early success return on line [[answer_line]] exits before the digest is finalized and the signature is checked, so malformed [[artifact]] values are treated as valid.",
            hints=(
                "The setup and cleanup code are fine.",
                "The flaw is a success path that happens too early.",
                "Look for a line that returns before the final verification step runs.",
                "The early return on line [[answer_line]] is the bug.",
            ),
            code=(
                "int verify_[[identifier_slug]](const ByteBuffer *[[artifact]], const Signature *signature) {",
                "    int status = 0;",
                "    HashContext hash_context;",
                "    ByteBuffer digest;",
                "    ByteBuffer metadata;",
                "",
                "    status = load_[[artifact]]_metadata([[artifact]], &metadata);",
                "    if (status != 0) {",
                "        return status;",
                "    }",
                "",
                "    status = init_hash(&hash_context, HASH_SHA256);",
                "    if (status != 0) {",
                "        free_buffer(&metadata);",
                "        return status;",
                "    }",
                "",
                "    status = hash_bytes(&hash_context, metadata.bytes, metadata.length);",
                "    if (status != 0) {",
                "        goto cleanup;",
                "    }",
                "",
                f"    {BUG_MARKER}return 0;",
                "",
                "    status = finish_hash(&hash_context, &digest);",
                "    if (status != 0) {",
                "        goto cleanup;",
                "    }",
                "",
                "    status = verify_signature(signature, &digest);",
                "",
                "cleanup:",
                "    free_buffer(&digest);",
                "    free_buffer(&metadata);",
                "    free_hash(&hash_context);",
                "    return status;",
                "}",
            ),
            variants=(
                {"slug": "firmware-bundle", "subject": "Firmware Bundle", "artifact": "bundle"},
                {"slug": "plugin-manifest", "subject": "Plugin Manifest", "artifact": "manifest"},
                {"slug": "backup-catalog", "subject": "Backup Catalog", "artifact": "catalog"},
                {"slug": "webhook-payload", "subject": "Webhook Payload", "artifact": "payload"},
                {"slug": "model-package", "subject": "Model Package", "artifact": "package"},
            ),
        ),
        PuzzleTemplate(
            key="authorization-bypass",
            language="Python",
            issue_category="Security and trust",
            issue_type="Authorization bypass",
            title="[[subject]] Edit Permission Check",
            source_note="Inspired by access-control bugs where a harmless-looking condition widens write access too far.",
            summary="This permission helper is almost reasonable. Find the line that grants edit access to the wrong audience.",
            explanation="The condition on line [[answer_line]] treats a publicly visible [[subject_lower]] as publicly editable. Visibility and edit authorization are different checks, so unauthorized users can modify content.",
            hints=(
                "The admin and owner checks are not the problem.",
                "The flaw confuses who may view a record with who may change it.",
                "Find the line that returns success for a broad audience without checking write permission.",
                "The public-visibility shortcut on line [[answer_line]] is the bug.",
            ),
            code=(
                "def can_edit_[[identifier_slug]](user, [[record]], team_lookup):",
                "    if user is None:",
                "        return False",
                "",
                "    if user.is_admin:",
                "        return True",
                "",
                "    team = team_lookup([[record]].team_id)",
                "    if team is None:",
                "        return False",
                "",
                "    if [[record]].owner_id == user.id:",
                "        return True",
                "",
                "    if user.id in team.editor_ids:",
                "        return True",
                "",
                "    if [[record]].locked:",
                "        return False",
                "",
                f"    {BUG_MARKER}if [[record]].visibility == \"public\":",
                "        return True",
                "",
                "    audit_log = {",
                "        \"record_id\": [[record]].id,",
                "        \"user_id\": user.id,",
                "        \"team_id\": [[record]].team_id,",
                "    }",
                "    return False",
            ),
            variants=(
                {"slug": "status-page", "subject": "Status Page", "subject_lower": "status page", "record": "page"},
                {"slug": "incident-report", "subject": "Incident Report", "subject_lower": "incident report", "record": "report"},
                {"slug": "vendor-profile", "subject": "Vendor Profile", "subject_lower": "vendor profile", "record": "profile"},
                {"slug": "release-note", "subject": "Release Note", "subject_lower": "release note", "record": "note"},
                {"slug": "support-playbook", "subject": "Support Playbook", "subject_lower": "support playbook", "record": "playbook"},
            ),
        ),
        PuzzleTemplate(
            key="trust-boundary-header",
            language="Python",
            issue_category="Security and trust",
            issue_type="Trust boundary violation",
            title="[[subject]] Header Identity Resolver",
            source_note="Inspired by bugs that trust caller-controlled headers as if they were authoritative identity records.",
            summary="This request-to-account mapper looks tidy. Find the one line that crosses the trust boundary incorrectly.",
            explanation="Line [[answer_line]] accepts a caller-controlled header as the account identity. An attacker can send any [[header_name]] value and act as another account.",
            hints=(
                "The parsing code is not the main issue.",
                "One branch trusts data from outside the authenticated session.",
                "Look for a line that treats client-supplied metadata as authoritative identity.",
                "The header lookup on line [[answer_line]] is the bug.",
            ),
            code=(
                "def resolve_[[identifier_slug]]_account(request, session_store, account_repo):",
                "    session_id = request.cookies.get(\"session_id\")",
                "    if not session_id:",
                "        return None",
                "",
                "    session = session_store.get(session_id)",
                "    if session is None:",
                "        return None",
                "",
                "    if session.revoked:",
                "        return None",
                "",
                "    account = account_repo.find_by_id(session.account_id)",
                "    if account is None:",
                "        return None",
                "",
                f"    {BUG_MARKER}header_account_id = request.headers.get(\"[[header_name]]\")",
                "    if header_account_id:",
                "        account = account_repo.find_by_id(header_account_id)",
                "",
                "    if account is None:",
                "        return None",
                "",
                "    if not account.active:",
                "        return None",
                "",
                "    return {",
                "        \"account_id\": account.id,",
                "        \"role\": account.role,",
                "    }",
            ),
            variants=(
                {"slug": "billing", "subject": "Billing", "header_name": "X-Account-Id"},
                {"slug": "console", "subject": "Admin Console", "header_name": "X-User-Id"},
                {"slug": "support", "subject": "Support", "header_name": "X-Act-As"},
                {"slug": "api", "subject": "Partner API", "header_name": "X-Customer-Id"},
                {"slug": "download", "subject": "Download", "header_name": "X-License-Owner"},
            ),
        ),
        PuzzleTemplate(
            key="insecure-default-toggle",
            language="Go",
            issue_category="Security and trust",
            issue_type="Insecure default",
            title="[[subject]] Transport Config Loader",
            source_note="Inspired by configuration parsers that silently fall back to a dangerously permissive default.",
            summary="Review this config loader and find the line that makes the safe path opt-in instead of default.",
            explanation="The assignment on line [[answer_line]] enables plaintext transport when the configuration omits the field. That makes the insecure mode the default behavior.",
            hints=(
                "The bug is in the fallback behavior, not the explicit configuration branches.",
                "One default value quietly weakens transport security.",
                "Look for a line that chooses the permissive mode when input is missing.",
                "The insecure default on line [[answer_line]] is the problem.",
            ),
            code=(
                "type [[config_type]]Config struct {",
                "    Endpoint       string",
                "    AllowPlaintext *bool",
                "    TimeoutSeconds int",
                "}",
                "",
                "func Load[[subject_compact]]Config(raw map[string]any) [[config_type]]Config {",
                "    cfg := [[config_type]]Config{",
                "        Endpoint:       rawString(raw, \"endpoint\"),",
                "        TimeoutSeconds: rawInt(raw, \"timeout_seconds\", 15),",
                "    }",
                "",
                "    if endpoint, ok := raw[\"endpoint\"].(string); ok && endpoint != \"\" {",
                "        cfg.Endpoint = endpoint",
                "    }",
                "",
                "    if value, ok := raw[\"allow_plaintext\"].(bool); ok {",
                "        cfg.AllowPlaintext = &value",
                "    } else {",
                f"        {BUG_MARKER}allow := true",
                "        cfg.AllowPlaintext = &allow",
                "    }",
                "",
                "    if cfg.Endpoint == \"\" {",
                "        cfg.Endpoint = \"https://localhost\"",
                "    }",
                "",
                "    return cfg",
                "}",
            ),
            variants=(
                {"slug": "backup-agent", "subject": "Backup Agent", "subject_compact": "BackupAgent", "config_type": "BackupAgent"},
                {"slug": "metrics-relay", "subject": "Metrics Relay", "subject_compact": "MetricsRelay", "config_type": "MetricsRelay"},
                {"slug": "cluster-sync", "subject": "Cluster Sync", "subject_compact": "ClusterSync", "config_type": "ClusterSync"},
                {"slug": "license-checker", "subject": "License Checker", "subject_compact": "LicenseChecker", "config_type": "LicenseChecker"},
                {"slug": "build-cache", "subject": "Build Cache", "subject_compact": "BuildCache", "config_type": "BuildCache"},
            ),
        ),
        PuzzleTemplate(
            key="solidity-reentrancy",
            language="Solidity",
            issue_category="State and ordering",
            issue_type="Reentrancy",
            title="[[subject]] Payout Vault",
            source_note="Inspired by Ethereum payout flows that call untrusted recipients before internal state is updated.",
            summary="This vault payout path looks standard. Find the line that creates the reentrancy window.",
            explanation="The external value transfer on line [[answer_line]] happens before the sender's balance is reduced. A malicious recipient can re-enter while the old balance is still recorded.",
            hints=(
                "The amount checks are not the problem.",
                "The bug is about the order of external interaction and state update.",
                "Look for the line that hands control back to caller-controlled code too early.",
                "The external call on line [[answer_line]] is the bug.",
            ),
            code=(
                "pragma solidity ^0.8.20;",
                "",
                "contract [[contract_name]]Vault {",
                "    mapping(address => uint256) public balances;",
                "    event Payout(address indexed account, uint256 amount);",
                "",
                "    function deposit() external payable {",
                "        require(msg.value > 0, \"value required\");",
                "        balances[msg.sender] += msg.value;",
                "    }",
                "",
                "    function claim(uint256 amount) external {",
                "        uint256 balance = balances[msg.sender];",
                "        require(balance >= amount, \"insufficient balance\");",
                "        require(amount > 0, \"amount required\");",
                "",
                "        uint256 reserve = amount / 50;",
                "        uint256 payout = amount - reserve;",
                "        emit Payout(msg.sender, payout);",
                "",
                f"        {BUG_MARKER}(bool sent, ) = msg.sender.call{{value: payout}}(\"\");",
                "        require(sent, \"transfer failed\");",
                "",
                "        balances[msg.sender] = balance - amount;",
                "    }",
                "",
                "    function vaultBalance() external view returns (uint256) {",
                "        return address(this).balance;",
                "    }",
                "}",
            ),
            variants=(
                {"slug": "bounty", "subject": "Bounty", "contract_name": "Bounty"},
                {"slug": "grants", "subject": "Grants", "contract_name": "Grants"},
                {"slug": "rewards", "subject": "Rewards", "contract_name": "Rewards"},
                {"slug": "contributors", "subject": "Contributor", "contract_name": "Contributor"},
                {"slug": "airdrop", "subject": "Airdrop", "contract_name": "Airdrop"},
            ),
        ),
        PuzzleTemplate(
            key="shared-mutable-template",
            language="Python",
            issue_category="State and ordering",
            issue_type="Shared mutable state",
            title="[[subject]] Template Context Builder",
            source_note="Inspired by request builders that accidentally reuse the same mutable object across independent calls.",
            summary="This helper assembles a render context. Find the line that makes separate requests share mutable state.",
            explanation="Line [[answer_line]] stores the module-level list directly into each new context. Mutating one request's warnings mutates every later context that reuses the same shared list.",
            hints=(
                "The bug is not in the loop that appends items.",
                "A fresh request is expected to get independent state but does not.",
                "Look for the line that reuses a mutable object instead of copying it.",
                "The shared-list assignment on line [[answer_line]] is the bug.",
            ),
            code=(
                "DEFAULT_WARNINGS = [\"review pending\"]",
                "",
                "def build_[[identifier_slug]]_context(record, actor, include_history=False):",
                "    context = {",
                "        \"record_id\": record.id,",
                "        \"actor_id\": actor.id,",
                "        \"title\": record.title,",
                "    }",
                "",
                f"    {BUG_MARKER}context[\"warnings\"] = DEFAULT_WARNINGS",
                "    context[\"highlights\"] = []",
                "",
                "    if record.locked:",
                "        context[\"warnings\"].append(\"locked\")",
                "",
                "    if actor.is_admin:",
                "        context[\"highlights\"].append(\"admin-view\")",
                "",
                "    if include_history:",
                "        context[\"history\"] = [event.summary for event in record.history]",
                "    else:",
                "        context[\"history\"] = []",
                "",
                "    context[\"editable\"] = actor.id == record.owner_id",
                "    context[\"warning_count\"] = len(context[\"warnings\"])",
                "    context[\"history_count\"] = len(context[\"history\"])",
                "    return context",
            ),
            variants=(
                {"slug": "invoice", "subject": "Invoice"},
                {"slug": "deployment", "subject": "Deployment"},
                {"slug": "incident", "subject": "Incident"},
                {"slug": "vendor", "subject": "Vendor"},
                {"slug": "ticket", "subject": "Ticket"},
            ),
        ),
        PuzzleTemplate(
            key="initialization-order",
            language="Java",
            issue_category="State and ordering",
            issue_type="Initialization order bug",
            title="[[subject]] Startup Sequencer",
            source_note="Inspired by startup paths that kick off work before required configuration is initialized.",
            summary="Review this startup routine and find the one line that runs a dependency before it is ready.",
            explanation="The call on line [[answer_line]] starts dependent work before the configuration object is loaded. The worker reads uninitialized state and can fail unpredictably.",
            hints=(
                "The bug is about ordering, not the exception handling.",
                "A later line initializes something that an earlier line already uses.",
                "Look for the first side effect that depends on configuration.",
                "The premature start call on line [[answer_line]] is the problem.",
            ),
            code=(
                "public final class [[class_name]]Startup {",
                "    private final [[config_name]]Config configLoader;",
                "    private [[config_name]]Config config;",
                "    private [[service_name]]Service service;",
                "",
                "    public [[class_name]]Startup([[config_name]]Config configLoader) {",
                "        this.configLoader = configLoader;",
                "    }",
                "",
                "    public void boot() {",
                "        service = new [[service_name]]Service();",
                "        service.setLogger(System.out::println);",
                "",
                f"        {BUG_MARKER}service.start(config);",
                "",
                "        config = configLoader.load();",
                "        if (config == null) {",
                "            throw new IllegalStateException(\"config required\");",
                "        }",
                "",
                "        service.setEndpoint(config.endpoint());",
                "        service.setRegion(config.region());",
                "        service.enableMetrics(config.metricsEnabled());",
                "        service.markReady();",
                "    }",
                "}",
            ),
            variants=(
                {"slug": "scheduler", "subject": "Scheduler", "class_name": "Scheduler", "config_name": "Scheduler", "service_name": "Scheduler"},
                {"slug": "telemetry", "subject": "Telemetry", "class_name": "Telemetry", "config_name": "Telemetry", "service_name": "Telemetry"},
                {"slug": "indexer", "subject": "Indexer", "class_name": "Indexer", "config_name": "Indexer", "service_name": "Indexer"},
                {"slug": "notifier", "subject": "Notifier", "class_name": "Notifier", "config_name": "Notifier", "service_name": "Notifier"},
                {"slug": "importer", "subject": "Importer", "class_name": "Importer", "config_name": "Importer", "service_name": "Importer"},
            ),
        ),
        PuzzleTemplate(
            key="stale-state-update",
            language="TypeScript",
            issue_category="State and ordering",
            issue_type="Stale state update",
            title="[[subject]] Counter Hook",
            source_note="Inspired by UI state bugs that update from a stale captured value instead of the latest committed state.",
            summary="This hook tracks pending work. Find the line that can drop increments under concurrent updates.",
            explanation="Line [[answer_line]] reads a captured [[state_name]] value and writes back a derived result. If multiple updates are queued together, later commits can overwrite earlier increments.",
            hints=(
                "The effect cleanup is not the issue.",
                "The flaw appears when several updates happen close together.",
                "Look for a state setter that should use the current value instead of a captured one.",
                "The non-functional state update on line [[answer_line]] is the bug.",
            ),
            code=(
                "import { useCallback, useMemo, useState } from \"react\";",
                "",
                "export function use[[hook_name]]Counter() {",
                "  const [[state_name]], set[[state_name_title]] = useState(0);",
                "  const [lastEvent, setLastEvent] = useState<string | null>(null);",
                "",
                "  const markQueued = useCallback((eventName: string) => {",
                "    setLastEvent(eventName);",
                f"    {BUG_MARKER}set[[state_name_title]]([[state_name]] + 1);",
                "  }, [[[state_name]]]);",
                "",
                "  const markFinished = useCallback(() => {",
                "    set[[state_name_title]]((current) => Math.max(0, current - 1));",
                "  }, []);",
                "",
                "  const summary = useMemo(() => {",
                "    if ([[state_name]] === 0) {",
                "      return \"idle\";",
                "    }",
                "    if ([[state_name]] === 1) {",
                "      return \"1 item pending\";",
                "    }",
                "    return `${[[state_name]]} items pending`;",
                "  }, [[[state_name]]]);",
                "",
                "  return {",
                "    pending: [[state_name]],",
                "    lastEvent,",
                "    summary,",
                "    markQueued,",
                "    markFinished,",
                "  };",
                "}",
            ),
            variants=(
                {"slug": "upload", "subject": "Upload", "hook_name": "Upload", "state_name": "pendingCount", "state_name_title": "PendingCount"},
                {"slug": "review", "subject": "Review", "hook_name": "Review", "state_name": "pendingReviews", "state_name_title": "PendingReviews"},
                {"slug": "sync", "subject": "Sync", "hook_name": "Sync", "state_name": "pendingJobs", "state_name_title": "PendingJobs"},
                {"slug": "import", "subject": "Import", "hook_name": "Import", "state_name": "pendingImports", "state_name_title": "PendingImports"},
                {"slug": "publish", "subject": "Publish", "hook_name": "Publish", "state_name": "pendingPublishes", "state_name_title": "PendingPublishes"},
            ),
        ),
        PuzzleTemplate(
            key="numeric-overflow",
            language="C",
            issue_category="Numeric correctness",
            issue_type="Numeric overflow / underflow",
            title="[[subject]] Buffer Sizer",
            source_note="Inspired by allocation math bugs where a multiplication silently overflows before memory is reserved.",
            summary="This allocator computes a buffer size from record counts. Find the arithmetic line that can wrap before allocation.",
            explanation="The multiplication on line [[answer_line]] is performed in a narrow integer type and can overflow before the result is widened for allocation. The allocated buffer can end up too small for the copy loop.",
            hints=(
                "The copy loop assumes the size calculation was correct.",
                "The problem happens before any memory is allocated.",
                "Look for arithmetic that can wrap when counts become large.",
                "The size multiplication on line [[answer_line]] is the bug.",
            ),
            code=(
                "uint8_t *build_[[identifier_slug]]_buffer(uint32_t record_count, uint32_t record_size) {",
                "    uint32_t index = 0;",
                "    uint32_t offset = 0;",
                "    uint8_t *buffer = NULL;",
                "    uint8_t fill_value = 0;",
                "",
                f"    {BUG_MARKER}uint32_t total_size = record_count * record_size;",
                "    if (total_size == 0) {",
                "        return NULL;",
                "    }",
                "",
                "    buffer = malloc(total_size);",
                "    if (buffer == NULL) {",
                "        return NULL;",
                "    }",
                "",
                "    fill_value = (uint8_t)(record_size & 0xff);",
                "    for (index = 0; index < record_count; index++) {",
                "        memset(buffer + offset, fill_value, record_size);",
                "        offset += record_size;",
                "        if (offset > total_size) {",
                "            break;",
                "        }",
                "    }",
                "",
                "    return buffer;",
                "}",
            ),
            variants=(
                {"slug": "telemetry", "subject": "Telemetry"},
                {"slug": "audit", "subject": "Audit"},
                {"slug": "snapshot", "subject": "Snapshot"},
                {"slug": "segment", "subject": "Segment"},
                {"slug": "index", "subject": "Index"},
            ),
        ),
        PuzzleTemplate(
            key="precision-loss-bigint",
            language="JavaScript",
            issue_category="Numeric correctness",
            issue_type="Precision loss",
            title="[[subject]] Duration Formatter",
            source_note="Inspired by telemetry code that converts large integers to floating-point too early and loses exactness.",
            summary="This formatter turns large nanosecond counters into readable output. Find the line that discards precision for big values.",
            explanation="Line [[answer_line]] converts a potentially huge BigInt into a Number before scaling. Large counters cannot be represented exactly as IEEE-754 doubles, so the displayed [[subject_lower]] duration can drift.",
            hints=(
                "The string formatting code is not the problem.",
                "A precise integer gets widened into a less precise representation too early.",
                "Look for the first conversion from BigInt-like data into Number.",
                "The numeric conversion on line [[answer_line]] is the bug.",
            ),
            code=(
                "export function format[[subject_compact]]Duration(sample) {",
                "  if (sample == null) {",
                "    return \"unknown\";",
                "  }",
                "",
                "  const totalNanos = sample.totalNanos;",
                "  if (typeof totalNanos !== \"bigint\") {",
                "    return \"invalid\";",
                "  }",
                "",
                f"  const micros = {BUG_MARKER}Number(totalNanos) / 1000;",
                "  const millis = micros / 1000;",
                "  const seconds = millis / 1000;",
                "",
                "  if (seconds >= 1) {",
                "    return `${seconds.toFixed(3)}s`;",
                "  }",
                "",
                "  if (millis >= 1) {",
                "    return `${millis.toFixed(2)}ms`;",
                "  }",
                "",
                "  if (micros >= 1) {",
                "    return `${micros.toFixed(1)}µs`;",
                "  }",
                "",
                "  return `${totalNanos}ns`;",
                "}",
            ),
            variants=(
                {"slug": "replication", "subject": "Replication", "subject_lower": "replication", "subject_compact": "Replication"},
                {"slug": "checkpoint", "subject": "Checkpoint", "subject_lower": "checkpoint", "subject_compact": "Checkpoint"},
                {"slug": "render", "subject": "Render", "subject_lower": "render", "subject_compact": "Render"},
                {"slug": "compile", "subject": "Compile", "subject_lower": "compile", "subject_compact": "Compile"},
                {"slug": "archive", "subject": "Archive", "subject_lower": "archive", "subject_compact": "Archive"},
            ),
        ),
        PuzzleTemplate(
            key="off-by-one-window",
            language="Rust",
            issue_category="Numeric correctness",
            issue_type="Off-by-one",
            title="[[subject]] Window Scanner",
            source_note="Inspired by slice-window loops that run one step too far and index beyond the final element.",
            summary="This scanner walks adjacent values. Find the loop boundary that steps one iteration too far.",
            explanation="The inclusive range on line [[answer_line]] allows the loop to run when index equals the last valid start position plus one. The code then reads past the end of the slice.",
            hints=(
                "The comparison inside the loop is fine.",
                "The bug is in how many iterations the loop allows.",
                "Look for a boundary that includes one case too many.",
                "The inclusive loop on line [[answer_line]] is the bug.",
            ),
            code=(
                "pub fn find_[[identifier_slug]]_drop(values: &[u32], threshold: u32) -> Option<usize> {",
                "    if values.len() < 2 {",
                "        return None;",
                "    }",
                "",
                "    let mut best_index = None;",
                "    let mut previous = values[0];",
                "",
                f"    for index in 1..={BUG_MARKER}values.len() {{",
                "        let current = values[index];",
                "        if previous.saturating_sub(current) >= threshold {",
                "            best_index = Some(index);",
                "            break;",
                "        }",
                "        previous = current;",
                "    }",
                "",
                "    if let Some(index) = best_index {",
                "        return Some(index);",
                "    }",
                "",
                "    None",
                "}",
            ),
            variants=(
                {"slug": "latency", "subject": "Latency"},
                {"slug": "pressure", "subject": "Pressure"},
                {"slug": "inventory", "subject": "Inventory"},
                {"slug": "throughput", "subject": "Throughput"},
                {"slug": "temperature", "subject": "Temperature"},
            ),
        ),
        PuzzleTemplate(
            key="unit-conversion-timeout",
            language="Kotlin",
            issue_category="Numeric correctness",
            issue_type="Unit conversion bug",
            title="[[subject]] Timeout Adapter",
            source_note="Inspired by integration bugs where milliseconds and seconds are mixed at an API boundary.",
            summary="This adapter forwards a configured timeout to a client library. Find the one line that sends the wrong unit.",
            explanation="The call on line [[answer_line]] passes a millisecond value into an API that expects seconds. The resulting timeout is thousands of times larger than intended.",
            hints=(
                "The parsed configuration value itself is fine.",
                "The mistake happens at the boundary between local code and a library API.",
                "Look for a line that forwards a duration without converting units.",
                "The timeout call on line [[answer_line]] is the bug.",
            ),
            code=(
                "class [[class_name]]ClientBuilder(private val config: Map<String, Int>) {",
                "    fun build(): [[class_name]]Client {",
                "        val timeoutMs = config[\"timeout_ms\"] ?: 5_000",
                "        val retries = config[\"retries\"] ?: 2",
                "        val client = [[class_name]]Client()",
                "",
                "        client.setRetries(retries)",
                "        client.setUserAgent(\"reviewdle/1.0\")",
                "",
                f"        client.setTimeoutSeconds({BUG_MARKER}timeoutMs)",
                "",
                "        if (timeoutMs <= 0) {",
                "            throw IllegalArgumentException(\"timeout must be positive\")",
                "        }",
                "",
                "        client.enableCompression(true)",
                "        client.enableMetrics(true)",
                "        return client",
                "    }",
                "}",
            ),
            variants=(
                {"slug": "storage", "subject": "Storage", "class_name": "Storage"},
                {"slug": "search", "subject": "Search", "class_name": "Search"},
                {"slug": "mailer", "subject": "Mailer", "class_name": "Mailer"},
                {"slug": "billing", "subject": "Billing", "class_name": "Billing"},
                {"slug": "queue", "subject": "Queue", "class_name": "Queue"},
            ),
        ),
        PuzzleTemplate(
            key="wrong-conditional",
            language="Python",
            issue_category="Control flow",
            issue_type="Wrong conditional logic",
            title="[[subject]] Token Guard",
            source_note="Inspired by boolean-condition bugs where one operator turns an authentication check inside out.",
            summary="This token validator is short and readable. Find the line where the condition means the opposite of what it should.",
            explanation="The condition on line [[answer_line]] uses `or`, so any non-null token passes even when it does not match the expected value. That defeats the intended guard.",
            hints=(
                "The parsing and expiration checks are okay.",
                "A single boolean operator makes the acceptance rule too broad.",
                "Look for a condition that should require two facts but only requires one.",
                "The token condition on line [[answer_line]] is the bug.",
            ),
            code=(
                "def validate_[[identifier_slug]]_token(provided_token, expected_token, expires_at, now):",
                "    if expected_token is None:",
                "        return False",
                "",
                "    if expires_at is None:",
                "        return False",
                "",
                "    if now >= expires_at:",
                "        return False",
                "",
                f"    if {BUG_MARKER}provided_token is not None or provided_token == expected_token:",
                "        return True",
                "",
                "    if provided_token == \"\":",
                "        return False",
                "",
                "    return False",
            ),
            variants=(
                {"slug": "reset", "subject": "Password Reset"},
                {"slug": "invite", "subject": "Invite"},
                {"slug": "download", "subject": "Download"},
                {"slug": "device", "subject": "Device Pairing"},
                {"slug": "api-key", "subject": "API Key"},
            ),
        ),
        PuzzleTemplate(
            key="premature-exit-retry",
            language="Go",
            issue_category="Control flow",
            issue_type="Premature exit",
            title="[[subject]] Retry Loop",
            source_note="Inspired by retry helpers that accidentally give up after the first failure instead of trying again.",
            summary="This helper intends to retry transient errors. Find the line that exits before later attempts can run.",
            explanation="The return on line [[answer_line]] leaves the function on the first failed attempt. The loop never reaches later retries, so transient failures are not retried.",
            hints=(
                "The sleep and success branch are fine.",
                "The function exits too early after an error.",
                "Look for a line inside the loop that should continue or wait instead of returning immediately.",
                "The early return on line [[answer_line]] is the bug.",
            ),
            code=(
                "func Send[[subject_compact]]WithRetry(client *Client, payload []byte) error {",
                "    var lastErr error",
                "",
                "    for attempt := 0; attempt < 3; attempt++ {",
                "        lastErr = client.Send(payload)",
                "        if lastErr == nil {",
                "            return nil",
                "        }",
                "",
                f"        {BUG_MARKER}return lastErr",
                "",
                "        if !client.ShouldRetry(lastErr) {",
                "            return lastErr",
                "        }",
                "",
                "        time.Sleep(100 * time.Millisecond)",
                "    }",
                "",
                "    return lastErr",
                "}",
            ),
            variants=(
                {"slug": "receipt", "subject": "Receipt", "subject_compact": "Receipt"},
                {"slug": "telemetry", "subject": "Telemetry", "subject_compact": "Telemetry"},
                {"slug": "invoice", "subject": "Invoice", "subject_compact": "Invoice"},
                {"slug": "event", "subject": "Event", "subject_compact": "Event"},
                {"slug": "snapshot", "subject": "Snapshot", "subject_compact": "Snapshot"},
            ),
        ),
        PuzzleTemplate(
            key="unreachable-recovery",
            language="Java",
            issue_category="Control flow",
            issue_type="Unreachable recovery path",
            title="[[subject]] Fallback Resolver",
            source_note="Inspired by fallback logic that looks present in the file but can never execute because of an earlier return.",
            summary="This resolver appears to have a backup path. Find the line that makes the recovery branch unreachable.",
            explanation="The return on line [[answer_line]] exits the method before the fallback branch can run when the primary lookup returns null. The intended recovery path is therefore unreachable.",
            hints=(
                "The fallback helper itself is fine.",
                "The bug is not a condition typo but a control-flow shortcut.",
                "Look for a return that happens before the code checks whether recovery is needed.",
                "The early return on line [[answer_line]] is the bug.",
            ),
            code=(
                "public final class [[class_name]]Resolver {",
                "    private final [[class_name]]Store primaryStore;",
                "    private final [[class_name]]Store fallbackStore;",
                "",
                "    public [[class_name]]Resolver([[class_name]]Store primaryStore, [[class_name]]Store fallbackStore) {",
                "        this.primaryStore = primaryStore;",
                "        this.fallbackStore = fallbackStore;",
                "    }",
                "",
                "    public [[class_name]]Record resolve(String key) {",
                "        [[class_name]]Record primary = primaryStore.get(key);",
                f"        {BUG_MARKER}return primary;",
                "",
                "        if (primary == null) {",
                "            return fallbackStore.get(key);",
                "        }",
                "",
                "        return primary.normalize();",
                "    }",
                "}",
            ),
            variants=(
                {"slug": "profile", "subject": "Profile", "class_name": "Profile"},
                {"slug": "policy", "subject": "Policy", "class_name": "Policy"},
                {"slug": "pricing", "subject": "Pricing", "class_name": "Pricing"},
                {"slug": "tenant", "subject": "Tenant", "class_name": "Tenant"},
                {"slug": "license", "subject": "License", "class_name": "License"},
            ),
        ),
        PuzzleTemplate(
            key="incorrect-loop-boundary",
            language="C#",
            issue_category="Control flow",
            issue_type="Incorrect loop boundary",
            title="[[subject]] Copier",
            source_note="Inspired by copy loops that iterate one element too far and step outside the valid range.",
            summary="This copy routine is simple. Find the loop boundary that overruns the source span.",
            explanation="The loop condition on line [[answer_line]] allows `index` to equal `count`. That causes the body to read one element past the last valid source position.",
            hints=(
                "The assignment inside the loop is fine.",
                "The bug is a boundary condition, not a bad index calculation later on.",
                "Look for a condition that includes an extra final iteration.",
                "The loop header on line [[answer_line]] is the bug.",
            ),
            code=(
                "public static class [[class_name]]Copier",
                "{",
                "    public static void Copy(Span<byte> destination, ReadOnlySpan<byte> source, int count)",
                "    {",
                "        if (count < 0)",
                "        {",
                "            throw new ArgumentOutOfRangeException(nameof(count));",
                "        }",
                "",
                f"        for (var index = 0; {BUG_MARKER}index <= count; index++)",
                "        {",
                "            destination[index] = source[index];",
                "        }",
                "",
                "        for (var index = count; index < destination.Length; index++)",
                "        {",
                "            destination[index] = 0;",
                "        }",
                "    }",
                "}",
            ),
            variants=(
                {"slug": "packet", "subject": "Packet", "class_name": "Packet"},
                {"slug": "frame", "subject": "Frame", "class_name": "Frame"},
                {"slug": "segment", "subject": "Segment", "class_name": "Segment"},
                {"slug": "token", "subject": "Token", "class_name": "Token"},
                {"slug": "payload", "subject": "Payload", "class_name": "Payload"},
            ),
        ),
        PuzzleTemplate(
            key="unchecked-return-value",
            language="C",
            issue_category="API and validation",
            issue_type="Unchecked return value",
            title="[[subject]] Metadata Writer",
            source_note="Inspired by low-level I/O paths that continue as if a critical write succeeded even when the API reports failure.",
            summary="This serializer writes several sections in order. Find the line where an API result is ignored.",
            explanation="Line [[answer_line]] calls a write routine but never checks whether it succeeded. If the write fails, later state assumes the header was persisted even though it was not.",
            hints=(
                "The cleanup logic is not the issue.",
                "A critical API tells the caller whether it succeeded, but that signal is discarded.",
                "Look for a line that calls an operation without validating its result.",
                "The unchecked write on line [[answer_line]] is the bug.",
            ),
            code=(
                "int write_[[identifier_slug]]_file(FileHandle *file, const Metadata *metadata) {",
                "    int status = 0;",
                "    Header header;",
                "    memset(&header, 0, sizeof(header));",
                "",
                "    header.version = 1;",
                "    header.flags = metadata->flags;",
                "    header.record_count = metadata->record_count;",
                "",
                f"    {BUG_MARKER}write_header(file, &header);",
                "",
                "    status = write_string(file, metadata->name);",
                "    if (status != 0) {",
                "        return status;",
                "    }",
                "",
                "    status = write_footer(file, metadata->checksum);",
                "    if (status != 0) {",
                "        return status;",
                "    }",
                "",
                "    return 0;",
                "}",
            ),
            variants=(
                {"slug": "catalog", "subject": "Catalog"},
                {"slug": "manifest", "subject": "Manifest"},
                {"slug": "snapshot", "subject": "Snapshot"},
                {"slug": "archive", "subject": "Archive"},
                {"slug": "checkpoint", "subject": "Checkpoint"},
            ),
        ),
        PuzzleTemplate(
            key="incorrect-api-sort",
            language="TypeScript",
            issue_category="API and validation",
            issue_type="Incorrect API usage",
            title="[[subject]] Priority Picker",
            source_note="Inspired by language APIs whose defaults look convenient but do the wrong thing for numeric data.",
            summary="This helper chooses the highest priority score. Find the line that misuses the sorting API.",
            explanation="Line [[answer_line]] relies on the default `sort()` behavior, which compares values as strings. Numeric priorities like 100 and 9 will therefore sort incorrectly.",
            hints=(
                "The map and filter steps are okay.",
                "The bug is not in the chosen data structure but in how a library call behaves by default.",
                "Look for an API whose default comparator is not numeric.",
                "The default sort call on line [[answer_line]] is the bug.",
            ),
            code=(
                "export function highest[[subject_compact]]Priority(items: Array<{ id: string; priority: number }>) {",
                "  const priorities = items",
                "    .filter((item) => Number.isFinite(item.priority))",
                "    .map((item) => item.priority);",
                "",
                "  if (priorities.length === 0) {",
                "    return null;",
                "  }",
                "",
                f"  priorities.{BUG_MARKER}sort();",
                "",
                "  const selectedPriority = priorities[priorities.length - 1];",
                "  return items.find((item) => item.priority === selectedPriority) ?? null;",
                "}",
            ),
            variants=(
                {"slug": "review", "subject": "Review", "subject_compact": "Review"},
                {"slug": "queue", "subject": "Queue", "subject_compact": "Queue"},
                {"slug": "alert", "subject": "Alert", "subject_compact": "Alert"},
                {"slug": "job", "subject": "Job", "subject_compact": "Job"},
                {"slug": "ticket", "subject": "Ticket", "subject_compact": "Ticket"},
            ),
        ),
        PuzzleTemplate(
            key="missing-null-handling",
            language="Kotlin",
            issue_category="API and validation",
            issue_type="Missing null handling",
            title="[[subject]] Contact Formatter",
            source_note="Inspired by nullable-data bugs where a convenience assertion crashes before the later null check can help.",
            summary="This formatter normalizes contact info. Find the line that dereferences a nullable value too early.",
            explanation="The non-null assertion on line [[answer_line]] dereferences a nullable field before the function validates it. A missing [[field_name]] will crash the formatter.",
            hints=(
                "The default return value is not the issue.",
                "A later guard exists, but it is too late to matter.",
                "Look for a line that assumes a nullable property is already present.",
                "The non-null assertion on line [[answer_line]] is the bug.",
            ),
            code=(
                "data class [[class_name]]Contact(val name: String?, val [[field_name]]: String?)",
                "",
                "fun format[[class_name]]Contact(contact: [[class_name]]Contact?): String {",
                "    if (contact == null) {",
                "        return \"unknown\"",
                "    }",
                "",
                f"    val normalized = contact.[[field_name]]{BUG_MARKER}!!.trim().lowercase()",
                "",
                "    if (contact.[[field_name]] == null) {",
                "        return \"unknown\"",
                "    }",
                "",
                "    val displayName = contact.name?.trim()?.ifEmpty { \"unknown\" } ?: \"unknown\"",
                "    return \"$displayName <$normalized>\"",
                "}",
            ),
            variants=(
                {"slug": "email", "subject": "Email", "class_name": "Email", "field_name": "address"},
                {"slug": "pager", "subject": "Pager", "class_name": "Pager", "field_name": "handle"},
                {"slug": "sms", "subject": "SMS", "class_name": "Sms", "field_name": "number"},
                {"slug": "slack", "subject": "Slack", "class_name": "Slack", "field_name": "channel"},
                {"slug": "billing", "subject": "Billing", "class_name": "Billing", "field_name": "email"},
            ),
        ),
        PuzzleTemplate(
            key="missing-bounds-validation",
            language="Rust",
            issue_category="API and validation",
            issue_type="Missing bounds validation",
            title="[[subject]] Selector",
            source_note="Inspired by parser bugs that trust an externally provided index without checking the valid range.",
            summary="This selector parses an index from input. Find the line that uses it before validating the bounds.",
            explanation="Line [[answer_line]] indexes into the collection with a parsed external value before checking whether it falls inside the valid range. An out-of-range input will panic.",
            hints=(
                "The parse step is not enough by itself.",
                "The flaw is not about the element type but about when validation occurs.",
                "Look for the first direct use of the parsed index.",
                "The unchecked index access on line [[answer_line]] is the bug.",
            ),
            code=(
                "pub fn select_[[identifier_slug]](items: &[String], raw_index: &str) -> Option<String> {",
                "    let index = raw_index.parse::<usize>().ok()?;",
                "",
                f"    let selected = {BUG_MARKER}items[index].clone();",
                "",
                "    if index >= items.len() {",
                "        return None;",
                "    }",
                "",
                "    if selected.is_empty() {",
                "        return None;",
                "    }",
                "",
                "    Some(selected)",
                "}",
            ),
            variants=(
                {"slug": "mirror", "subject": "Mirror"},
                {"slug": "region", "subject": "Region"},
                {"slug": "theme", "subject": "Theme"},
                {"slug": "adapter", "subject": "Adapter"},
                {"slug": "plan", "subject": "Plan"},
            ),
        ),
        PuzzleTemplate(
            key="resource-leak-temp",
            language="Python",
            issue_category="Resources and lifetime",
            issue_type="Resource leak",
            title="[[subject]] Temp File Loader",
            source_note="Inspired by error paths that return before a temporary file handle is cleaned up.",
            summary="This helper reads a temp file and validates its header. Find the line that leaks the resource on failure.",
            explanation="The return on line [[answer_line]] exits the function without closing the already-open file handle. Repeated failures can accumulate leaked descriptors.",
            hints=(
                "The happy path closes the file correctly.",
                "The flaw is on an error branch after the resource is acquired.",
                "Look for a line that returns before cleanup can happen.",
                "The early return on line [[answer_line]] is the bug.",
            ),
            code=(
                "def load_[[identifier_slug]]_preview(path):",
                "    handle = open(path, \"rb\")",
                "    header = handle.read(4)",
                "",
                "    if header != b\"CRDL\":",
                f"        {BUG_MARKER}return None",
                "",
                "    body = handle.read()",
                "    if not body:",
                "        handle.close()",
                "        return None",
                "",
                "    result = {",
                "        \"size\": len(body),",
                "        \"preview\": body[:16],",
                "    }",
                "    handle.close()",
                "    return result",
            ),
            variants=(
                {"slug": "sprite", "subject": "Sprite"},
                {"slug": "cache", "subject": "Cache"},
                {"slug": "bundle", "subject": "Bundle"},
                {"slug": "report", "subject": "Report"},
                {"slug": "patch", "subject": "Patch"},
            ),
        ),
        PuzzleTemplate(
            key="double-close-stream",
            language="Python",
            issue_category="Resources and lifetime",
            issue_type="Double free / double close",
            title="[[subject]] Stream Finalizer",
            source_note="Inspired by cleanup flows that close the same handle twice under normal execution.",
            summary="This finalizer looks defensive. Find the line that causes the same stream to be closed twice.",
            explanation="The explicit close on line [[answer_line]] happens inside a `with` block that already closes the stream automatically. Some wrappers react badly to the second close.",
            hints=(
                "The write calls are not the issue.",
                "The bug is in the cleanup strategy, not the success condition.",
                "Look for a resource that is already managed automatically.",
                "The redundant close on line [[answer_line]] is the bug.",
            ),
            code=(
                "def finalize_[[identifier_slug]]_stream(path, chunks):",
                "    with open(path, \"wb\") as handle:",
                "        for chunk in chunks:",
                "            if not chunk:",
                "                continue",
                "            handle.write(chunk)",
                "",
                "        handle.flush()",
                f"        {BUG_MARKER}handle.close()",
                "",
                "    return len(chunks)",
            ),
            variants=(
                {"slug": "export", "subject": "Export"},
                {"slug": "trace", "subject": "Trace"},
                {"slug": "archive", "subject": "Archive"},
                {"slug": "snapshot", "subject": "Snapshot"},
                {"slug": "invoice", "subject": "Invoice"},
            ),
        ),
        PuzzleTemplate(
            key="use-after-close-file",
            language="Python",
            issue_category="Resources and lifetime",
            issue_type="Use after free",
            title="[[subject]] Readback Helper",
            source_note="Inspired by lifetime bugs where code keeps using a resource after it has been released.",
            summary="This helper writes a footer and then inspects it. Find the line that uses the handle after it has been closed.",
            explanation="The read on line [[answer_line]] happens after the file handle has been closed. Using the released resource can fail immediately or behave inconsistently across wrappers.",
            hints=(
                "The footer calculation is not the problem.",
                "A resource is used after its lifetime has ended.",
                "Look for an operation that happens after an explicit close.",
                "The post-close read on line [[answer_line]] is the bug.",
            ),
            code=(
                "def inspect_[[identifier_slug]]_footer(path, footer):",
                "    handle = open(path, \"ab+\")",
                "    handle.write(footer)",
                "    handle.flush()",
                "    handle.seek(0)",
                "    handle.close()",
                "",
                f"    {BUG_MARKER}tail = handle.read()[-len(footer):]",
                "    return tail == footer",
            ),
            variants=(
                {"slug": "ledger", "subject": "Ledger"},
                {"slug": "audit", "subject": "Audit"},
                {"slug": "packet", "subject": "Packet"},
                {"slug": "build", "subject": "Build"},
                {"slug": "report", "subject": "Report"},
            ),
        ),
        PuzzleTemplate(
            key="dangling-reference-cpp",
            language="C++",
            issue_category="Resources and lifetime",
            issue_type="Dangling reference",
            title="[[subject]] Label Builder",
            source_note="Inspired by helpers that return references or pointers to local stack objects.",
            summary="This formatter returns a convenient view. Find the line that returns a reference to an object that is about to die.",
            explanation="The return on line [[answer_line]] exposes a reference to a local string. Once the function returns, that storage is gone and the caller holds a dangling reference.",
            hints=(
                "The concatenation logic is fine.",
                "The problem is about object lifetime after the function returns.",
                "Look for a returned reference or pointer tied to local storage.",
                "The return on line [[answer_line]] is the bug.",
            ),
            code=(
                "#include <string>",
                "",
                "const std::string& build_[[identifier_slug]]_label(const std::string& prefix, int number) {",
                "    std::string label = prefix;",
                "    label += \"-\";",
                "    label += std::to_string(number);",
                "",
                f"    {BUG_MARKER}return label;",
                "}",
            ),
            variants=(
                {"slug": "job", "subject": "Job"},
                {"slug": "ticket", "subject": "Ticket"},
                {"slug": "device", "subject": "Device"},
                {"slug": "invoice", "subject": "Invoice"},
                {"slug": "batch", "subject": "Batch"},
            ),
        ),
    )


def build_generated_puzzles() -> list[dict[str, object]]:
    items: list[dict[str, object]] = []
    for template in templates()[:20]:
        for variant in template.variants:
            items.append(render_puzzle(template, variant))
    if len(items) != 100:
        raise ValueError(f"Expected 100 generated puzzles, found {len(items)}")
    ids = [item["id"] for item in items]
    if len(ids) != len(set(ids)):
        raise ValueError("Generated puzzle ids are not unique.")
    return items


def main() -> None:
    puzzles = load_base_puzzles() + build_generated_puzzles()
    PUZZLE_BANK_PATH.write_text(json.dumps(puzzles, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(puzzles)} puzzles to {PUZZLE_BANK_PATH}")


if __name__ == "__main__":
    main()
