from __future__ import annotations

from .models import CardDefinition, CardKind, PassiveAbility


def starter_pool(owner_id: str) -> list[CardDefinition]:
    return [
        CardDefinition(
            card_id=f"{owner_id}-starter-brick-wall",
            name="Brick Wall Beetle",
            theme="stubborn plated beetle",
            prompt="starter defender beetle",
            owner_id=owner_id,
            kind=CardKind.UNIT,
            hp=8,
            attack=1,
            cpc=3,
            speed=1,
            attack_range=0,
            income=0,
            keywords=("Defender",),
            role_tags=("defender",),
            passive=PassiveAbility("fortify", 1, "Takes less damage while blocking."),
        ),
        CardDefinition(
            card_id=f"{owner_id}-starter-vine-cleric",
            name="Vine Cleric",
            theme="gentle healer woven from moss",
            prompt="starter healing support",
            owner_id=owner_id,
            kind=CardKind.UNIT,
            hp=4,
            attack=1,
            cpc=2,
            speed=1,
            attack_range=0,
            income=0,
            keywords=("Healing",),
            role_tags=("support",),
            passive=PassiveAbility("heal_base", 1, "Heals the base each round."),
        ),
        CardDefinition(
            card_id=f"{owner_id}-starter-gold-sprite",
            name="Gold Sprite",
            theme="small economy spirit",
            prompt="starter economy spirit",
            owner_id=owner_id,
            kind=CardKind.UNIT,
            hp=3,
            attack=1,
            cpc=2,
            speed=1,
            attack_range=0,
            income=0,
            keywords=(),
            role_tags=("economy",),
            passive=PassiveAbility("income_boost", 1, "Adds extra card points each round."),
        ),
        CardDefinition(
            card_id=f"{owner_id}-starter-lancer",
            name="Track Lancer",
            theme="disciplined spear runner",
            prompt="starter attacker lancer",
            owner_id=owner_id,
            kind=CardKind.UNIT,
            hp=4,
            attack=3,
            cpc=2,
            speed=1,
            attack_range=0,
            income=0,
            keywords=(),
            role_tags=("attacker",),
            passive=PassiveAbility("none", 0, "No passive ability."),
            art_variant_id="track-lancer-velocity-rare",
        ),
        CardDefinition(
            card_id=f"{owner_id}-starter-archer",
            name="Track Archer",
            theme="disciplined support sniper",
            prompt="starter ranged archer",
            owner_id=owner_id,
            kind=CardKind.UNIT,
            hp=3,
            attack=2,
            cpc=3,
            speed=1,
            attack_range=1,
            income=0,
            keywords=("Ranged",),
            role_tags=("ranged", "support"),
            passive=PassiveAbility("none", 0, "No passive ability."),
        ),
        CardDefinition(
            card_id=f"{owner_id}-starter-hawk",
            name="Sky Hawk",
            theme="flying ambusher",
            prompt="starter flying hawk",
            owner_id=owner_id,
            kind=CardKind.UNIT,
            hp=3,
            attack=3,
            cpc=4,
            speed=2,
            attack_range=0,
            income=0,
            keywords=("Flying",),
            role_tags=("attacker",),
            passive=PassiveAbility("none", 0, "No passive ability."),
        ),
    ]
